def draw_restaurant():
    print("restaurant not found")
return
def draw_restaurant(height=3)
    print("=============================================")
    print("||               PAVEMENT                  ||")
    print("=============================================")
    print("||         \_________________/             ||")
    print("||         |___50% off all___|             ||")
    for i in range(height):
        print("||                                         ||")
    print("||                   ___________________   ||")
    print("||                   |        |        |   ||")
    print("||                   |        |        |   ||")
    print("||                   |        |        |   ||")
    print("||                   |        |        |   ||")
    print("||===================|       *|*       |   ||")
    print("||_____ _____ _____  |       *|*       |   ||")
    print("||  |     |     |    |        |        |   ||")
    print("||  |     |     |    |        |        |   ||")
    print("||  |     |     |    |        |        |   ||")
    print("||  |     |     |    |        |        |   ||")
    print("=============================================")
    print("=============================================")
    return